dist: trusty
sudo: required
services:
  - docker

env:
  global:
  - DOCKER_VERSION=1.13.1-0~ubuntu-trusty
  matrix:
  - TEST_TARGET: travis-cli

before_install:
  # list docker-engine versions
  - apt-cache madison docker-engine
  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y --force-yes docker-engine=${DOCKER_VERSION}
  - docker version
  - docker info

script:
  - make $TEST_TARGET

notifications:
  slack:
    secure: E589tdwh2aXMTBHdCib6TdjeQPMcd4vM0sydSjxxki0r8mk7k2Wwl+tladkvbDtJXn+URr33Bv2e7FWwFDKn6kK6GCQFBl/W2/0PZ6PrscevAu5OWOW521sY0MpQrF1fL34xBuQBGzROZq52ClbQ7s1KviYOCrbLeYHgL2FGkNi0hrHtW1GotWJpbpbSNQT9De4Lce7u6Go+voeZzAWfnCNxRGb3ibTN5P14Bdn4f+qDSOyU9Ml1AiUUpq3bWGkahBwJgAs+PvjE5vsv6Eoyp02GyHdnSwUJAKtGV1DUGWBv/v3slm8ozMNG8o2qU0e8hp+CprArQvpbT+m1ZmclMzcAorAhxbnDZTmv9DLkk1ScvtDZ/rrtaTYoLc+b31lFwqa4LRSRQPNVjQiANy1AYo+jFFwxTMNta4508czoC2G3PiR1Wcmw2rpDgWIg/b0DyA6hy/IRdmvsLv4fR97J99nf4sn+0hwn7C9dvqSg27svgxBHBFuEaCIBzfWLkORulfMP5dA3a2H2p7w6bbw0z+lrPu7PNuWH644sTfRKdXSh08nnLBsHTNnI1tHccvkB/C2PM/+HJkd1EGrIvie8P35fwb7TK/KeHOdFY+dtTIp6jdCvmqI887ALqWjpt/pVZdRZLq3a+LFrQdVbKX/sj4F+3l4u8mAW6OO64a+0l4U=