dist: trusty
sudo: required
services:
  - docker

env:
  global:
  - DOCKER_VERSION=1.13.1-0~ubuntu-trusty
  matrix:
  - TEST_TARGET: travis-cli

before_install:
  # list docker-engine versions
  - apt-cache madison docker-engine
  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y --force-yes docker-engine=${DOCKER_VERSION}
  - docker version
  - docker info

script:
  - make $TEST_TARGET